### PR TITLE
Joined template to server

### PR DESCRIPTION
**Pull request by zachary-trudo**
Problem: Our template and server were two different sets of software.

Solution: Joined them like a boss.

File changes:
- chatAppTemplate folder:
  - Removed
  - Contents moved to appropriate locations in server folder
- SERVER/main.py
  - Created functions for grabbing js, css, and image resources.
  - Created function for rendering chatApp.html
- SERVER/templates folder:
  - Replaced index with our login page.

### CODE REVIEW

**Comment by zachary-trudo** [comment]
@adamcarlton @adibb Please do code reviews.

@adamcarlton DO NOT MERGE THIS OR I WILL NOT BE HAPPY. YOU SEE THE MERGE BUTTON? DON'T HIT IT.

**Review by adamcarlton — APPROVED** [review]
LGTM

**Comment by adibb** [comment]
LGTM. Took a bit to find that you'd moved the login page to index.html, but that was all.

EDIT: Dang it, where's that approve button?

EDIT 2 (Electric Boogaloo): Oh, nevermind. Looks like Adam was the only actual 'reviewer'. That explains it.

**Review by adibb — APPROVED** [review]
Nevermind again! Found it!

**Pull request merged**
